### ISSUE TITLE
Should check for notice when new companies are added

### ISSUE THREAD

**Issue by sanderdatema** [jplattel/berichtenbox-forwarder#1]
If there are companies added to this site, you will first see a notice about that after logging in. That will make the script fail.

(superfijn script! ;)

**Comment by jplattel** [comment]
@sanderdatema Ja, goed dat je het zegt, ik ga daar denk ik nog even een check voor inbouwen :+1:

**Comment by arondeparon** [comment]
Just implemented this in https://github.com/jplattel/berichtenbox-forwarder/pull/2

**Comment by jplattel** [comment]
@sanderdatema this is fixed now thanks to @ArondeParon , just a heads up :)
